# Generated by Django 5.2.3 on 2025-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_appointment_options_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-Show"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="is_verified",
        ),
    ]
