# Generated by Django 5.2.3 on 2025-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appointment_doctor_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
