# Generated by Django 5.2.3 on 2025-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='building',
            field=models.CharField(blank=True, choices=[('Building 1', 'Building 1'), ('Building 2', 'Building 2'), ('Building 3', 'Building 3'), ('Hospital Pharmacy', 'Hospital Pharmacy')], max_length=50, null=True),
        ),
    ]
