# Generated by Django 5.2.3 on 2025-07-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_doctor_appointment_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permanent_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="temporary_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
